project:
  type: book
  output-dir: _site

book:
  title: "Solving the MCP Tool Adoption Problem: A Behavioral Framework for Automatic Tool Usage in AI Systems"
  subtitle: "Bridging the Gap Between Tool Availability and Tool Utilization"
  author:
    - name: "Scot Campbell"
      affiliation: "Independent Researcher"
      email: "scott@simpleminded.bot"
      orcid: "0000-0000-0000-0000"
  date: "2025-09-17"
  chapters:
    - index.qmd
    - sections/01-introduction.qmd
    - sections/02-background.qmd
    - sections/03-methodology.qmd
    - sections/04-framework.qmd
    - sections/05-implementation.qmd
    - sections/06-evaluation.qmd
    - sections/07-discussion.qmd
    - sections/08-conclusion.qmd
    - sections/references.qmd

bibliography: references.bib
csl: ieee.csl

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-summary: "Show code"
  pdf:
    documentclass: article
    classoption: [11pt, a4paper]
    geometry: [margin=1in]
    fontfamily: times
    fontsize: 11pt
    linestretch: 1.5
    bibliography: references.bib
    citeproc: true
    number-sections: true
    fig-cap-location: bottom
    tbl-cap-location: top
    crossref:
      fig-title: "Figure"
      tbl-title: "Table"
      eq-title: "Equation"
    include-in-header:
      - text: |
          \usepackage{amsmath}
          \usepackage{amsfonts}
          \usepackage{amssymb}
          \usepackage{algorithm}
          \usepackage{algorithmic}

execute:
  echo: false
  warning: false
  message: false