project:
  type: book
  output-dir: _site

book:
  title: "AUTOPILOT: A Hierarchical Framework for Autonomous Tool Usage in AI Systems"
  subtitle: "Autonomous User Tool Optimization through Proactive Intelligent Learning and Organized Testing"
  author:
    - name: "Scot Campbell"
      affiliation: "Independent Researcher"
      email: "scott@simpleminded.bot"
      orcid: "0000-0000-0000-0000"
  date: "2025-09-17"
  chapters:
    - index.qmd
    - sections/01-introduction.qmd
    - sections/02-related-work.qmd
    - sections/03-autopilot-framework.qmd
    - sections/04-implementation.qmd
    - sections/05-evaluation.qmd
    - sections/06-discussion.qmd
    - sections/07-conclusion.qmd
    - sections/references.qmd

bibliography: references.bib
csl: neurips.csl

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
  pdf:
    documentclass: article
    classoption: [11pt, a4paper]
    geometry: [margin=1in]
    fontfamily: times
    fontsize: 11pt
    linestretch: 1.5
    bibliography: references.bib
    citeproc: true
    number-sections: true
    fig-cap-location: bottom
    tbl-cap-location: top
    include-in-header:
      - text: |
          \usepackage{amsmath}
          \usepackage{amsfonts}
          \usepackage{amssymb}
          \usepackage{algorithm}
          \usepackage{algorithmic}
          \usepackage{booktabs}

execute:
  echo: false
  warning: false
  message: false