project:
  type: book
  output-dir: _site

book:
  title: "The Tool Adoption Gap in AI Systems"
  subtitle: "An Empirical Study of Availability vs. Utilization"
  author:
    - name: "Scot Campbell"
      affiliation: "Independent Researcher"
      email: "scott@simpleminded.bot"
      orcid: "0000-0000-0000-0000"
  date: "2025-09-17"
  chapters:
    - index.qmd
    - sections/01-introduction.qmd
    - sections/02-literature-review.qmd
    - sections/03-methodology.qmd
    - sections/04-results.qmd
    - sections/05-discussion.qmd
    - sections/06-conclusion.qmd
    - sections/references.qmd

bibliography: references.bib
csl: acm-sigchi-proceedings.csl

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
  pdf:
    documentclass: acmart
    classoption: [sigchi, review, anonymous]
    geometry: [margin=1in]
    fontsize: 10pt
    linestretch: 1.0
    bibliography: references.bib
    citeproc: true
    number-sections: true
    fig-cap-location: bottom
    tbl-cap-location: top

execute:
  echo: false
  warning: false
  message: false